/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Modelo.Users;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import controladores.Controlador;
import controladores.controladorIndex;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.JTableHeader;

/**
 *
 * @author samue, Jd
 */
public class index extends javax.swing.JFrame {

    public String principalColor = "#852121", segundoColor = "#531415", tercerColor = "#601d49";

    /**
     * Creates new form index
     */
    private Modelo.Users user;
    public index() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new MiWindowAdapter());
        
        this.setIconImage(new ImageIcon(index.class.getResource("/img/icon.png")).getImage());
        
        Info in = new Info();
        showPanel(in);
        

        
        addFlatLaf();

    }
    controladorIndex objControladorIndex = new controladorIndex();
    private int layoutX;
    private int layoutY;
     public void addFlatLaf(){
        try {
            Color hoverBckgroundColor = new Color(96,29,73);
            UIManager.put("nimbusBlueGrey", Color.decode(tercerColor));
            
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Component.focusWidht",1);
            SwingUtilities.updateComponentTreeUI(this);      
            
            UIManager.put("TableHeader.hoverBackground",hoverBckgroundColor);
            
            SwingUtilities.updateComponentTreeUI(this);
            
        } catch (Exception e) {
        }
    }
    

    private static class MiWindowAdapter extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            int opc = JOptionPane.showConfirmDialog(null, "Quiere cerrar sesion y salir?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
            if (opc == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
    }

    private String rol;

    /*public index(int rol){
        this.rol = rol;
    //Constructor para obtener el rol
    
    }*/
    public void setUserName(String name) {
        this.userName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGesUsuarios3 = new javax.swing.JPanel();
        labelPerfil4 = new javax.swing.JLabel();
        btnGesUsuarios5 = new javax.swing.JPanel();
        labelPerfil6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconUsers1 = new javax.swing.JLabel();
        iconUsers2 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        menuLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        labelInicio = new javax.swing.JLabel();
        iconInicio = new javax.swing.JLabel();
        textBiene = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPerfil = new javax.swing.JPanel();
        labelPerfil = new javax.swing.JLabel();
        iconUser = new javax.swing.JLabel();
        btnProductos = new javax.swing.JPanel();
        labelProductos = new javax.swing.JLabel();
        iconProductos = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        labelUsuarios = new javax.swing.JLabel();
        iconUsers = new javax.swing.JLabel();
        btnPedidos = new javax.swing.JPanel();
        labelPerfil8 = new javax.swing.JLabel();
        iconPedidos = new javax.swing.JLabel();
        btnReservas = new javax.swing.JPanel();
        labelPerfil9 = new javax.swing.JLabel();
        iconReservas = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpanelMain = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        btnGesUsuarios3.setBackground(new java.awt.Color(133, 33, 33));
        btnGesUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGesUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGesUsuarios3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGesUsuarios3MouseExited(evt);
            }
        });

        labelPerfil4.setBackground(new java.awt.Color(255, 206, 172));
        labelPerfil4.setFont(new java.awt.Font("Boring Sans A Trial", 0, 18)); // NOI18N
        labelPerfil4.setForeground(new java.awt.Color(255, 206, 172));
        labelPerfil4.setText("Usuarios");

        javax.swing.GroupLayout btnGesUsuarios3Layout = new javax.swing.GroupLayout(btnGesUsuarios3);
        btnGesUsuarios3.setLayout(btnGesUsuarios3Layout);
        btnGesUsuarios3Layout.setHorizontalGroup(
            btnGesUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGesUsuarios3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelPerfil4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGesUsuarios3Layout.setVerticalGroup(
            btnGesUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGesUsuarios3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(labelPerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnGesUsuarios5.setBackground(new java.awt.Color(133, 33, 33));
        btnGesUsuarios5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGesUsuarios5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGesUsuarios5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGesUsuarios5MouseExited(evt);
            }
        });

        labelPerfil6.setBackground(new java.awt.Color(255, 206, 172));
        labelPerfil6.setFont(new java.awt.Font("Boring Sans A Trial", 0, 18)); // NOI18N
        labelPerfil6.setForeground(new java.awt.Color(255, 206, 172));
        labelPerfil6.setText("Usuarios");

        javax.swing.GroupLayout btnGesUsuarios5Layout = new javax.swing.GroupLayout(btnGesUsuarios5);
        btnGesUsuarios5.setLayout(btnGesUsuarios5Layout);
        btnGesUsuarios5Layout.setHorizontalGroup(
            btnGesUsuarios5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGesUsuarios5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelPerfil6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGesUsuarios5Layout.setVerticalGroup(
            btnGesUsuarios5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGesUsuarios5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(labelPerfil6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Pizzeria La Romana le da la bienvenida!");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 700));

        panelContent.setLayout(new java.awt.BorderLayout());

        menuLateral.setBackground(new java.awt.Color(133, 33, 33));
        menuLateral.setPreferredSize(new java.awt.Dimension(260, 602));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prueba2.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(133, 33, 33));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });

        labelInicio.setBackground(new java.awt.Color(255, 206, 172));
        labelInicio.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelInicio.setForeground(new java.awt.Color(255, 206, 172));
        labelInicio.setText("Inicio");

        iconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(labelInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        textBiene.setFont(new java.awt.Font("Boring Sans A Trial", 0, 18)); // NOI18N
        textBiene.setForeground(new java.awt.Color(255, 255, 255));
        textBiene.setText("Bienvenido:");

        userName.setBackground(new java.awt.Color(245, 245, 205));
        userName.setFont(new java.awt.Font("Boring Sans A Trial", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("Usuario");

        jSeparator1.setBackground(new java.awt.Color(255, 206, 172));
        jSeparator1.setForeground(new java.awt.Color(255, 206, 172));

        btnPerfil.setBackground(new java.awt.Color(133, 33, 33));
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
        });

        labelPerfil.setBackground(new java.awt.Color(255, 206, 172));
        labelPerfil.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelPerfil.setForeground(new java.awt.Color(255, 206, 172));
        labelPerfil.setText("Perfil");

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconUser)
                .addGap(55, 55, 55)
                .addComponent(labelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addGroup(btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        btnProductos.setBackground(new java.awt.Color(133, 33, 33));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });

        labelProductos.setBackground(new java.awt.Color(255, 206, 172));
        labelProductos.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelProductos.setForeground(new java.awt.Color(255, 206, 172));
        labelProductos.setText("Productos");

        iconProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/products.png"))); // NOI18N

        javax.swing.GroupLayout btnProductosLayout = new javax.swing.GroupLayout(btnProductos);
        btnProductos.setLayout(btnProductosLayout);
        btnProductosLayout.setHorizontalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProductosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(labelProductos)
                .addGap(89, 89, 89))
        );
        btnProductosLayout.setVerticalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosLayout.createSequentialGroup()
                .addGroup(btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        btnUsuarios.setBackground(new java.awt.Color(133, 33, 33));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });

        labelUsuarios.setBackground(new java.awt.Color(255, 206, 172));
        labelUsuarios.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelUsuarios.setForeground(new java.awt.Color(255, 206, 172));
        labelUsuarios.setText("Usuarios");

        iconUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N

        javax.swing.GroupLayout btnUsuariosLayout = new javax.swing.GroupLayout(btnUsuarios);
        btnUsuarios.setLayout(btnUsuariosLayout);
        btnUsuariosLayout.setHorizontalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUsuariosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(labelUsuarios)
                .addGap(105, 105, 105))
        );
        btnUsuariosLayout.setVerticalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addGroup(btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnPedidos.setBackground(new java.awt.Color(133, 33, 33));
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPedidosMouseExited(evt);
            }
        });

        labelPerfil8.setBackground(new java.awt.Color(255, 206, 172));
        labelPerfil8.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelPerfil8.setForeground(new java.awt.Color(255, 206, 172));
        labelPerfil8.setText("Pedidos");

        iconPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N

        javax.swing.GroupLayout btnPedidosLayout = new javax.swing.GroupLayout(btnPedidos);
        btnPedidos.setLayout(btnPedidosLayout);
        btnPedidosLayout.setHorizontalGroup(
            btnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedidosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iconPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(labelPerfil8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        btnPedidosLayout.setVerticalGroup(
            btnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedidosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPerfil8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnReservas.setBackground(new java.awt.Color(133, 33, 33));
        btnReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReservasMouseExited(evt);
            }
        });

        labelPerfil9.setBackground(new java.awt.Color(255, 206, 172));
        labelPerfil9.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelPerfil9.setForeground(new java.awt.Color(255, 206, 172));
        labelPerfil9.setText("Mesas");

        iconReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.png"))); // NOI18N

        javax.swing.GroupLayout btnReservasLayout = new javax.swing.GroupLayout(btnReservas);
        btnReservas.setLayout(btnReservasLayout);
        btnReservasLayout.setHorizontalGroup(
            btnReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconReservas)
                .addGap(59, 59, 59)
                .addComponent(labelPerfil9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        btnReservasLayout.setVerticalGroup(
            btnReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelPerfil9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(iconReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        btnSalir.setBackground(new java.awt.Color(133, 33, 33));
        btnSalir.setPreferredSize(new java.awt.Dimension(281, 52));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        labelSalir.setBackground(new java.awt.Color(255, 206, 172));
        labelSalir.setFont(new java.awt.Font("Boring Sans A Trial", 0, 20)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(255, 206, 172));
        labelSalir.setText("Salir");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(labelSalir)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLateralLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textBiene)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userName))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBiene)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.add(menuLateral, java.awt.BorderLayout.LINE_START);

        panelRight.setBackground(new java.awt.Color(245, 245, 205));
        panelRight.setPreferredSize(new java.awt.Dimension(500, 550));
        panelRight.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(133, 33, 33));
        panelHeader.setPreferredSize(new java.awt.Dimension(100, 150));
        panelHeader.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelTapiz3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMinimumSize(new java.awt.Dimension(204, 300));
        jLabel4.setPreferredSize(new java.awt.Dimension(254, 300));
        panelHeader.add(jLabel4, "card2");

        panelRight.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        jpanelMain.setBackground(new java.awt.Color(245, 245, 205));
        jpanelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanelMain.setPreferredSize(new java.awt.Dimension(777, 396));
        jpanelMain.setLayout(new java.awt.CardLayout());
        panelRight.add(jpanelMain, java.awt.BorderLayout.CENTER);

        panelContent.add(panelRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        panelTitle.setBackground(new java.awt.Color(109, 21, 22));
        panelTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelTitle.setPreferredSize(new java.awt.Dimension(1037, 40));
        panelTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTitleMouseDragged(evt);
            }
        });
        panelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTitleMousePressed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setPreferredSize(new java.awt.Dimension(35, 50));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maximize.png"))); // NOI18N
        maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maximize.setPreferredSize(new java.awt.Dimension(35, 50));
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.setPreferredSize(new java.awt.Dimension(35, 50));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBla.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 885, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(maximize, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        getContentPane().add(panelTitle, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGesUsuarios3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesUsuarios3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGesUsuarios3MouseEntered

    private void btnGesUsuarios3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesUsuarios3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGesUsuarios3MouseExited

    private void btnGesUsuarios5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesUsuarios5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGesUsuarios5MouseEntered

    private void btnGesUsuarios5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesUsuarios5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGesUsuarios5MouseExited

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:

        Users modLogin = new Users();
        login visLogin = new login();

        int opc = JOptionPane.showConfirmDialog(null, "¿Quiere cerrar sesion??", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
        if (opc == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Controlador ctrl = new Controlador(visLogin, modLogin);
            ctrl.iniciar();
        }

    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnReservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseExited
        // TODO add your handling code here:
        btnReservas.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnReservasMouseExited

    private void btnReservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseEntered
        // TODO add your handling code here:
        btnReservas.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnReservasMouseEntered

    private void btnReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseClicked
        // TODO add your handling code here:
        Mesas rs = new Mesas();
        showPanel(rs);
    }//GEN-LAST:event_btnReservasMouseClicked

    private void btnPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseExited
        // TODO add your handling code here:
        btnPedidos.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnPedidosMouseExited

    private void btnPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseEntered
        // TODO add your handling code here:
        btnPedidos.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnPedidosMouseEntered

    private void btnPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseClicked
        // TODO add your handling code here:
        Pedidos pd = new Pedidos();
        showPanel(pd);
    }//GEN-LAST:event_btnPedidosMouseClicked

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        // TODO add your handling code here:
        btnUsuarios.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        // TODO add your handling code
        btnUsuarios.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        // TODO add your handling code here:
        Usuarios us = new Usuarios();
        showPanel(us);

    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        // TODO add your handling code here:
        btnProductos.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        // TODO add your handling code here:
        btnProductos.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
        // TODO add your handling code here:
        Productos pr = new Productos();
        showPanel(pr);
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        btnPerfil.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        btnPerfil.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        Perfil p = new Perfil(this, true, this);
        objControladorIndex.mostrarDatos(p, user.getIdUsuario());
        p.setLocationRelativeTo(null);
        p.setVisible(true);

    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:    String principalColor = "852121";

        btnInicio.setBackground(Color.decode(principalColor));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:

        btnInicio.setBackground(Color.decode(segundoColor));
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        Info info = new Info();
        showPanel(info);
    }//GEN-LAST:event_btnInicioMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            if (this.getExtendedState() == MAXIMIZED_BOTH) {
                this.setExtendedState(NORMAL);
                //flagExtendedState = false;
            } else {
                this.setExtendedState(MAXIMIZED_BOTH);
                //flagExtendedState = true;
            }
        }
    }//GEN-LAST:event_maximizeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_minimizeMouseClicked

    private void panelTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTitleMousePressed
        // TODO add your handling code here:
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            layoutX = evt.getX();
            layoutY = evt.getY();
        }
    }//GEN-LAST:event_panelTitleMousePressed

    private void panelTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTitleMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - layoutX, evt.getYOnScreen() - layoutY);
    }//GEN-LAST:event_panelTitleMouseDragged

    public void runView(String rol, Modelo.Users user) {
        this.user = user;
        this.rol = rol;
        if (!rol.equals("super_admin")) {
            btnUsuarios.setVisible(false);
            btnProductos.setVisible(false);
        }
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGesUsuarios3;
    private javax.swing.JPanel btnGesUsuarios5;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnPedidos;
    public javax.swing.JPanel btnPerfil;
    private javax.swing.JPanel btnProductos;
    private javax.swing.JPanel btnReservas;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JLabel close;
    private javax.swing.JLabel iconInicio;
    private javax.swing.JLabel iconPedidos;
    private javax.swing.JLabel iconProductos;
    private javax.swing.JLabel iconReservas;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel iconUsers;
    private javax.swing.JLabel iconUsers1;
    private javax.swing.JLabel iconUsers2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpanelMain;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel labelPerfil4;
    private javax.swing.JLabel labelPerfil6;
    private javax.swing.JLabel labelPerfil8;
    private javax.swing.JLabel labelPerfil9;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelSalir;
    private javax.swing.JLabel labelUsuarios;
    private javax.swing.JLabel maximize;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JLabel textBiene;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    protected void tableColor(JTableHeader t) {
        t.setForeground(Color.WHITE);

        Font headerFont = new Font("Boring sans", Font.BOLD, 14);
        t.setFont(headerFont);

        t.repaint();
    }
    
   
    

    private void showPanel(JPanel p) {
//        p.setSize(921, 505);
//        p.setLocation(0, 0);

        jpanelMain.removeAll();
        jpanelMain.add(p, BorderLayout.CENTER);
        jpanelMain.revalidate();
        jpanelMain.repaint();
    }

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody

    }
}
