/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.ControladorInfo;
import java.sql.SQLException;

/**
 *
 * @author samue, Jd
 */
public class Info extends javax.swing.JPanel {

    /**
     * Creates new form Info
     */
    public Info(){
        initComponents();
        mostrarNumUsuariosEnVista();
        mostrarNumProductosEnVista();
        mostrarNumPedidosEnVista();
        mostrarNumMesasEnVista();
    }

    ControladorInfo controlador = new ControladorInfo();
     private void mostrarNumUsuariosEnVista(){
         int numUsuarios = controlador.contar_num_usuarios(); // Manejar excepciones
         cantUsers.setText(String.valueOf(numUsuarios));
    }
     
     private void mostrarNumProductosEnVista() {
         int numProductos = controlador.contar_num_productos(); // Manejar excepciones
         cantProductos.setText(String.valueOf(numProductos));
    }
     
     private void mostrarNumPedidosEnVista() {
         int numPedidos = controlador.contar_num_pedidos(); // Manejar excepciones
         cantPedidos.setText(String.valueOf(numPedidos));
    }
    
     private void mostrarNumMesasEnVista() {
         int numMesas = controlador.contar_num_mesas(); // Manejar excepciones
         cantReservas.setText(String.valueOf(numMesas));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardProductos = new javax.swing.JPanel();
        labelPA = new javax.swing.JLabel();
        iconProductsCard = new javax.swing.JLabel();
        cantProductos = new javax.swing.JLabel();
        cardUsuarios = new javax.swing.JPanel();
        labelPA1 = new javax.swing.JLabel();
        iconUserCard = new javax.swing.JLabel();
        cantUsers = new javax.swing.JLabel();
        cardReservas = new javax.swing.JPanel();
        labelMR = new javax.swing.JLabel();
        iconReservasCard = new javax.swing.JLabel();
        cantReservas = new javax.swing.JLabel();
        cardPedidos1 = new javax.swing.JPanel();
        labelPP = new javax.swing.JLabel();
        iconPedidosCard = new javax.swing.JLabel();
        cantPedidos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 220));
        setLayout(new java.awt.GridBagLayout());

        panelInfo.setBackground(new java.awt.Color(245, 245, 220));
        panelInfo.setForeground(new java.awt.Color(150, 50, 50));
        panelInfo.setMinimumSize(new java.awt.Dimension(940, 480));
        panelInfo.setPreferredSize(new java.awt.Dimension(940, 480));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Boring Sans A Trial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 21, 22));
        jLabel1.setText("Información General");

        jSeparator1.setForeground(new java.awt.Color(85, 21, 22));

        cardProductos.setBackground(new java.awt.Color(255, 255, 255));
        cardProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 50, 50)));

        labelPA.setBackground(new java.awt.Color(255, 255, 255));
        labelPA.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPA.setForeground(new java.awt.Color(150, 50, 50));
        labelPA.setText("Productos añadidos");

        iconProductsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productsCard.png"))); // NOI18N

        cantProductos.setBackground(new java.awt.Color(255, 255, 255));
        cantProductos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantProductos.setForeground(new java.awt.Color(150, 50, 50));
        cantProductos.setText("1");

        javax.swing.GroupLayout cardProductosLayout = new javax.swing.GroupLayout(cardProductos);
        cardProductos.setLayout(cardProductosLayout);
        cardProductosLayout.setHorizontalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProductosLayout.createSequentialGroup()
                        .addComponent(labelPA)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProductosLayout.createSequentialGroup()
                        .addComponent(cantProductos)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProductosLayout.createSequentialGroup()
                        .addComponent(iconProductsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        cardProductosLayout.setVerticalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconProductsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        cardUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        cardUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 21, 22)));

        labelPA1.setBackground(new java.awt.Color(255, 255, 255));
        labelPA1.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPA1.setForeground(new java.awt.Color(150, 50, 50));
        labelPA1.setText("Usuarios añadidos");

        iconUserCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usersCard3.png"))); // NOI18N

        cantUsers.setBackground(new java.awt.Color(255, 255, 255));
        cantUsers.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantUsers.setForeground(new java.awt.Color(150, 50, 50));
        cantUsers.setText("1");

        javax.swing.GroupLayout cardUsuariosLayout = new javax.swing.GroupLayout(cardUsuarios);
        cardUsuarios.setLayout(cardUsuariosLayout);
        cardUsuariosLayout.setHorizontalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUsuariosLayout.createSequentialGroup()
                .addGroup(cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardUsuariosLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cantUsers))
                    .addGroup(cardUsuariosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelPA1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconUserCard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        cardUsuariosLayout.setVerticalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconUserCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPA1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        cardReservas.setBackground(new java.awt.Color(255, 255, 255));
        cardReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 50, 50)));

        labelMR.setBackground(new java.awt.Color(255, 255, 255));
        labelMR.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelMR.setForeground(new java.awt.Color(150, 50, 50));
        labelMR.setText("Numero de mesas");

        iconReservasCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesaGrande.png"))); // NOI18N

        cantReservas.setBackground(new java.awt.Color(255, 255, 255));
        cantReservas.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantReservas.setForeground(new java.awt.Color(150, 50, 50));
        cantReservas.setText("1");

        javax.swing.GroupLayout cardReservasLayout = new javax.swing.GroupLayout(cardReservas);
        cardReservas.setLayout(cardReservasLayout);
        cardReservasLayout.setHorizontalGroup(
            cardReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardReservasLayout.createSequentialGroup()
                        .addComponent(cantReservas)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardReservasLayout.createSequentialGroup()
                        .addComponent(labelMR)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardReservasLayout.createSequentialGroup()
                        .addComponent(iconReservasCard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        cardReservasLayout.setVerticalGroup(
            cardReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardReservasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconReservasCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        cardPedidos1.setBackground(new java.awt.Color(255, 255, 255));
        cardPedidos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 50, 50)));

        labelPP.setBackground(new java.awt.Color(255, 255, 255));
        labelPP.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPP.setForeground(new java.awt.Color(150, 50, 50));
        labelPP.setText("Pedidos Pendientes");

        iconPedidosCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidosCard.png"))); // NOI18N

        cantPedidos.setBackground(new java.awt.Color(255, 255, 255));
        cantPedidos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantPedidos.setForeground(new java.awt.Color(150, 50, 50));
        cantPedidos.setText("1");

        javax.swing.GroupLayout cardPedidos1Layout = new javax.swing.GroupLayout(cardPedidos1);
        cardPedidos1.setLayout(cardPedidos1Layout);
        cardPedidos1Layout.setHorizontalGroup(
            cardPedidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPedidos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardPedidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPedidos1Layout.createSequentialGroup()
                        .addComponent(iconPedidosCard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPedidos1Layout.createSequentialGroup()
                        .addComponent(cantPedidos)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPedidos1Layout.createSequentialGroup()
                        .addComponent(labelPP)
                        .addGap(16, 16, 16))))
        );
        cardPedidos1Layout.setVerticalGroup(
            cardPedidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPedidos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPedidosCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(labelPP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                .addGap(490, 490, 490))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardPedidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(160, 160, 160)))
                .addGap(31, 31, 31))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPedidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(panelInfo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantPedidos;
    private javax.swing.JLabel cantProductos;
    private javax.swing.JLabel cantReservas;
    private javax.swing.JLabel cantUsers;
    private javax.swing.JPanel cardPedidos1;
    private javax.swing.JPanel cardProductos;
    private javax.swing.JPanel cardReservas;
    private javax.swing.JPanel cardUsuarios;
    private javax.swing.JLabel iconPedidosCard;
    private javax.swing.JLabel iconProductsCard;
    private javax.swing.JLabel iconReservasCard;
    private javax.swing.JLabel iconUserCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMR;
    private javax.swing.JLabel labelPA;
    private javax.swing.JLabel labelPA1;
    private javax.swing.JLabel labelPP;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables
}
