/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.ControladorInfo;
import java.sql.SQLException;

/**
 *
 * @author samue, Jd
 */
public class Info extends javax.swing.JPanel {

    /**
     * Creates new form Info
     */
    public Info(){
        initComponents();
        mostrarNumUsuariosEnVista();
        mostrarNumProductosEnVista();
        mostrarNumPedidosEnVista();
        mostrarNumMesasEnVista();
    }

    ControladorInfo controlador = new ControladorInfo();
     private void mostrarNumUsuariosEnVista(){
         int numUsuarios = controlador.contar_num_usuarios(); // Manejar excepciones
         cantUsers.setText(String.valueOf(numUsuarios));
    }
     
     private void mostrarNumProductosEnVista() {
         int numProductos = controlador.contar_num_productos(); // Manejar excepciones
         cantProductos.setText(String.valueOf(numProductos));
    }
     
     private void mostrarNumPedidosEnVista() {
         int numPedidos = controlador.contar_num_pedidos(); // Manejar excepciones
         cantPedidos.setText(String.valueOf(numPedidos));
    }
    
     private void mostrarNumMesasEnVista() {
         int numMesas = controlador.contar_num_mesas(); // Manejar excepciones
         cantReservas.setText(String.valueOf(numMesas));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardProductos = new javax.swing.JPanel();
        labelPA = new javax.swing.JLabel();
        iconProductsCard = new javax.swing.JLabel();
        cantProductos = new javax.swing.JLabel();
        cardUsuarios = new javax.swing.JPanel();
        labelPA1 = new javax.swing.JLabel();
        iconUserCard = new javax.swing.JLabel();
        cantUsers = new javax.swing.JLabel();
        cardReservas = new javax.swing.JPanel();
        labelMR = new javax.swing.JLabel();
        iconReservasCard = new javax.swing.JLabel();
        cantReservas = new javax.swing.JLabel();
        cardPedidos1 = new javax.swing.JPanel();
        labelPP = new javax.swing.JLabel();
        iconPedidosCard = new javax.swing.JLabel();
        cantPedidos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 220));
        setLayout(new java.awt.GridBagLayout());

        panelInfo.setBackground(new java.awt.Color(245, 245, 220));
        panelInfo.setForeground(new java.awt.Color(150, 50, 50));
        panelInfo.setMinimumSize(new java.awt.Dimension(940, 480));
        panelInfo.setPreferredSize(new java.awt.Dimension(940, 480));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Boring Sans A Trial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 21, 22));
        jLabel1.setText("Información General");

        jSeparator1.setForeground(new java.awt.Color(85, 21, 22));

        cardProductos.setBackground(new java.awt.Color(253, 253, 253));
        cardProductos.setPreferredSize(new java.awt.Dimension(252, 155));
        cardProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPA.setBackground(new java.awt.Color(255, 255, 255));
        labelPA.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPA.setForeground(new java.awt.Color(150, 50, 50));
        labelPA.setText("Productos añadidos");
        cardProductos.add(labelPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 74, -1, 29));

        iconProductsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productsCard.png"))); // NOI18N
        cardProductos.add(iconProductsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 12, 60, -1));

        cantProductos.setBackground(new java.awt.Color(255, 255, 255));
        cantProductos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantProductos.setForeground(new java.awt.Color(150, 50, 50));
        cantProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantProductos.setText("1");
        cardProductos.add(cantProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 109, 100, 34));

        cardUsuarios.setBackground(new java.awt.Color(253, 253, 253));
        cardUsuarios.setPreferredSize(new java.awt.Dimension(252, 155));
        cardUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPA1.setBackground(new java.awt.Color(255, 255, 255));
        labelPA1.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPA1.setForeground(new java.awt.Color(150, 50, 50));
        labelPA1.setText("Usuarios añadidos");
        cardUsuarios.add(labelPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 77, -1, 29));

        iconUserCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usersCard3.png"))); // NOI18N
        cardUsuarios.add(iconUserCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 15, 60, 56));

        cantUsers.setBackground(new java.awt.Color(255, 255, 255));
        cantUsers.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantUsers.setForeground(new java.awt.Color(150, 50, 50));
        cantUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantUsers.setText("1");
        cardUsuarios.add(cantUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 113, 100, 34));

        cardReservas.setBackground(new java.awt.Color(253, 253, 253));
        cardReservas.setPreferredSize(new java.awt.Dimension(252, 155));
        cardReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMR.setBackground(new java.awt.Color(255, 255, 255));
        labelMR.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelMR.setForeground(new java.awt.Color(150, 50, 50));
        labelMR.setText("Numero de mesas");
        cardReservas.add(labelMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 74, -1, 29));

        iconReservasCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesaGrande.png"))); // NOI18N
        cardReservas.add(iconReservasCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 12, 60, 56));

        cantReservas.setBackground(new java.awt.Color(255, 255, 255));
        cantReservas.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantReservas.setForeground(new java.awt.Color(150, 50, 50));
        cantReservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantReservas.setText("1");
        cardReservas.add(cantReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 109, 100, 34));

        cardPedidos1.setBackground(new java.awt.Color(253, 253, 253));
        cardPedidos1.setPreferredSize(new java.awt.Dimension(252, 155));
        cardPedidos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPP.setBackground(new java.awt.Color(255, 255, 255));
        labelPP.setFont(new java.awt.Font("Boring Sans A Trial", 1, 24)); // NOI18N
        labelPP.setForeground(new java.awt.Color(150, 50, 50));
        labelPP.setText("Pedidos Pendientes");
        cardPedidos1.add(labelPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 78, -1, 29));

        iconPedidosCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidosCard.png"))); // NOI18N
        cardPedidos1.add(iconPedidosCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 10, -1, -1));

        cantPedidos.setBackground(new java.awt.Color(255, 255, 255));
        cantPedidos.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cantPedidos.setForeground(new java.awt.Color(150, 50, 50));
        cantPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantPedidos.setText("1");
        cardPedidos1.add(cantPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 113, 100, 34));

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                .addGap(490, 490, 490))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardPedidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(160, 160, 160)))
                .addGap(31, 31, 31))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPedidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(panelInfo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantPedidos;
    private javax.swing.JLabel cantProductos;
    private javax.swing.JLabel cantReservas;
    private javax.swing.JLabel cantUsers;
    private javax.swing.JPanel cardPedidos1;
    private javax.swing.JPanel cardProductos;
    private javax.swing.JPanel cardReservas;
    private javax.swing.JPanel cardUsuarios;
    private javax.swing.JLabel iconPedidosCard;
    private javax.swing.JLabel iconProductsCard;
    private javax.swing.JLabel iconReservasCard;
    private javax.swing.JLabel iconUserCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMR;
    private javax.swing.JLabel labelPA;
    private javax.swing.JLabel labelPA1;
    private javax.swing.JLabel labelPP;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables
}
