/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.FlowLayout;
import controladores.ControladorMesas;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samue, Jd
 */
public class Mesas extends javax.swing.JPanel {

    /**
     * Creates new form Reservas
     */
    public Mesas() {
        initComponents();
        
        tableModel();
        fillRows();
    }
    
    private DefaultTableModel modelTable;
    private List<Modelo.Mesas> listaMesas;
    private ControladorMesas conObject = new ControladorMesas();

    int rowSelected = -1;
    
    public void tableModel() {
        modelTable = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        modelTable.addColumn("Numero");
        modelTable.addColumn("Nombre");
        modelTable.addColumn("Estado");

        tableMesas.setModel(modelTable);
        
        tableMesas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void fillRows() {

        modelTable.setRowCount(0);
        listaMesas = conObject.getListaMesas();
        
        listaMesas.forEach(l -> {
            String estado = getNombreDisponibilidad(l.getEstado());
            modelTable.addRow(new Object[]{l.getIdMesa(),getNombreMesa(l.getNumero_mesa()), estado});
        });
    }
    public String getNombreDisponibilidad(int state) {

        String nombre = "";
        if (state== 0) {
            nombre = "Ocupado";
        } else if (state == 1) {
            nombre = "disponible";
        }

        return nombre;

    }
    
    public String getNombreMesa(int id){
        
        String nombreMesa = "Mesa " + String.valueOf(id);
        
        return nombreMesa;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitlePedidos = new javax.swing.JLabel();
        panelReservas = new javax.swing.JPanel();
        contentScroll = new javax.swing.JScrollPane();
        labelTitleMesas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumMesa = new javax.swing.JTextField();
        txtNombreMesa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMesas = new javax.swing.JTable();
        cmbState = new javax.swing.JComboBox<>();
        btnEditarMesa = new javax.swing.JButton();
        btnAgregarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();

        labelTitlePedidos.setBackground(new java.awt.Color(255, 255, 255));
        labelTitlePedidos.setFont(new java.awt.Font("Boring Sans A Trial", 1, 36)); // NOI18N
        labelTitlePedidos.setForeground(new java.awt.Color(96, 29, 73));
        labelTitlePedidos.setText("Gestionar Pedidos");

        panelReservas.setBackground(new java.awt.Color(245, 245, 220));
        panelReservas.setForeground(new java.awt.Color(96, 29, 73));

        labelTitleMesas.setBackground(new java.awt.Color(255, 255, 255));
        labelTitleMesas.setFont(new java.awt.Font("Boring Sans A Trial", 1, 36)); // NOI18N
        labelTitleMesas.setForeground(new java.awt.Color(96, 29, 73));
        labelTitleMesas.setText("Gestion de mesas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Numero mesa:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre mesa(opcional):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Estado:");

        txtNumMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumMesaActionPerformed(evt);
            }
        });

        tableMesas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Estado"
            }
        ));
        tableMesas.setShowHorizontalLines(true);
        tableMesas.setShowVerticalLines(true);
        tableMesas.getTableHeader().setResizingAllowed(false);
        tableMesas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableMesas);

        cmbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditarMesa.setBackground(new java.awt.Color(96, 29, 73));
        btnEditarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMesa.setText("Editar");
        btnEditarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMesaActionPerformed(evt);
            }
        });

        btnAgregarMesa.setBackground(new java.awt.Color(96, 29, 73));
        btnAgregarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMesa.setText("Agregar");

        btnEliminarMesa.setBackground(new java.awt.Color(133, 33, 33));
        btnEliminarMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMesa.setText("Eliminar");

        javax.swing.GroupLayout panelReservasLayout = new javax.swing.GroupLayout(panelReservas);
        panelReservas.setLayout(panelReservasLayout);
        panelReservasLayout.setHorizontalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelReservasLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(39, 39, 39)
                            .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(182, 182, 182)
                            .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btnEditarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelReservasLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelTitleMesas, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        panelReservasLayout.setVerticalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitleMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditarMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMesaActionPerformed

    private void txtNumMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMesa;
    private javax.swing.JButton btnEditarMesa;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JComboBox<String> cmbState;
    private javax.swing.JScrollPane contentScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitleMesas;
    private javax.swing.JLabel labelTitlePedidos;
    private javax.swing.JPanel panelReservas;
    private javax.swing.JTable tableMesas;
    private javax.swing.JTextField txtNombreMesa;
    private javax.swing.JTextField txtNumMesa;
    // End of variables declaration//GEN-END:variables
    
   
}

